id: I61059426
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:23:39+00:00'
last_modified: '2022-06-09T04:31:02.811967+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24750
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་རིག་གནས་ཀྱི་རྣམ་བཤད་རྟོག་གེའི་གཟི་མདངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    96C1:
      image_group_id: I1KG24752
      title: Volume 1 of bod kyi srol rgyun rig gnas kyi rnam bzhag rtog ge'i gzi
        mdangs/
      total_pages: 475
      order: 1
      base_file: 96C1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
