id: P008103
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24750
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་རིག་གནས་ཀྱི་རྣམ་བཤད་རྟོག་གེའི་གཟི་མདངས།
  author: ''
  volumes:
    bc2688a42e80488a843246df3711eb4f:
      image_group_id: I1KG24752
      title: ''
      volume_number: 1
      total_pages: 475
ebook_metadata:
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་རིག་གནས་ཀྱི་རྣམ་བཤད་རྟོག་གེའི་གཟི་མདངས།
  author: ''
  sku: P008103
  cover: cover.jpg
  layers:
  - pagination
