id: P008103
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 13:01:45.504717
source_metadata:
  id: bdr:W1KG24750
  title: བོད་ཀྱི་སྲོལ་རྒྱུན་རིག་གནས་ཀྱི་རྣམ་བཤད་རྟོག་གེའི་གཟི་མདངས།
  author: ''
  volumes:
    804c9f51e11a4edf940dfebc1e67ec8a:
      image_group_id: I1KG24752
      title: Volume 1 of bod kyi srol rgyun rig gnas kyi rnam bzhag rtog ge'i gzi
        mdangs/
      volume_number: 1
      total_pages: 475
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
